show databases;
use mysql;

CREATE  TABLE if not exists Supplier(
SUPP_ID INT NOT NULL PRIMARY KEY,
SUPP_NAME varchar(50)NOT NULL,
SUPP_CITY varchar(50)NOT NULL ,
SUPP_PHONE varchar(50)NOT NULL);
CREATE TABLE IF NOT EXISTS `customer` ( 
`CUS_ID` INT NOT NULL PRIMARY KEY, 
`CUS_NAME` VARCHAR(20) NOT NULL, 
`CUS_PHONE` VARCHAR(10) NOT NULL, 
`CUS_CITY` varchar(30) NOT NULL, 
`CUS_GENDER` CHAR); 
CREATE TABLE IF NOT EXISTS `category` ( 
`CAT_ID` INT NOT NULL PRIMARY KEY, 
`CAT_NAME` VARCHAR(20) NOT NULL 
); 
CREATE TABLE IF NOT EXISTS `product` ( 
`PRO_ID` INT NOT NULL PRIMARY KEY, 
`PRO_NAME` VARCHAR(20) NOT NULL DEFAULT "Dummy Product",
 `PRO_DESC` VARCHAR(60), 
`CAT_ID` INT NOT NULL, 
FOREIGN KEY (`CAT_ID`) REFERENCES CATEGORY (`CAT_ID`) );
CREATE TABLE IF NOT EXISTS `supplier_pricing` ( 
`PRICING_ID` INT NOT NULL primary key, 
`PRO_ID` INT NOT NULL, 
`SUPP_ID` INT NOT NULL, 
`SUPP_PRICE` INT DEFAULT 0, 
FOREIGN KEY (`PRO_ID`) REFERENCES PRODUCT (`PRO_ID`), FOREIGN KEY (`SUPP_ID`) REFERENCES SUPPLIER(`SUPP_ID`) ); 
CREATE TABLE IF NOT EXISTS `order` ( 
`ORD_ID` INT NOT NULL PRIMARY KEY, 
`ORD_AMOUNT` INT NOT NULL, 
`ORD_DATE` DATE, 
`CUS_ID` INT NOT NULL, 
`PRICING_ID` INT NOT NULL, 
FOREIGN KEY (`CUS_ID`) REFERENCES CUSTOMER(`CUS_ID`), FOREIGN KEY (`PRICING_ID`) REFERENCES SUPPLIER_PRICING(`PRICING_ID`) ); 
CREATE TABLE IF NOT EXISTS `rating` ( 
`RAT_ID` INT NOT NULL PRIMARY KEY, 
`ORD_ID` INT NOT NULL, 
`RAT_RATSTARS` INT NOT NULL, 
FOREIGN KEY (`ORD_ID`) REFERENCES `ORDER` (`ORD_ID`) );
